name: .NET Test Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore UITests/UITests.csproj

      - name: Build
        run: dotnet build UITests/UITests.csproj --configuration Release

      - name: Run tests
        run: dotnet test UITests/UITests.csproj --no-build --configuration Release --verbosity normal
