name: .NET Test Automation CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '9.0.x'

      - name: Restore dependencies
        run: dotnet restore UITests/UITests.csproj

      - name: Build
        run: dotnet build UITests/UITests.csproj --configuration Release

      - name: Set environment variables from secrets
        run: |
          echo "RYANAIR_EMAIL=${{ secrets.RYANAIR_EMAIL }}" >> $GITHUB_ENV
          echo "RYANAIR_PASSWORD=${{ secrets.RYANAIR_PASSWORD }}" >> $GITHUB_ENV

      - name: Run tests and generate Allure results
        run: |
          dotnet test UITests/UITests.csproj \
            --no-build \
            --configuration Release \
            --logger:"console;verbosity=normal"

      - name: Load Allure report history
        uses: actions/checkout@v3
        if: always()
        continue-on-error: true
        with:
          ref: gh-pages
          path: gh-pages

      - name: Build Allure report
        uses: simple-elf/allure-report-action@v1.7
        if: always()
        with:
          gh_pages: gh-pages
          allure_results: UITests/bin/Release/net6.0/allure-results
          allure_history: allure-history

      - name: Publish Allure report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        if: always()
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: allure-history
